import { useContext } from "react";
import FeedbackContext from "../contexts/FeedbackContext";

export const useFeedbacks = () => {
  const {
    shimmerEffect,
    feedback,
    onSignupSubmit,
    signupError,
    user,
    formError,
    onFeedbackSubmit,
    uniqueId,
    onLoginSubmit,
    loginError,
    formValue,
    setFormValue,
    setFeedbacks,
    onFeedbackDelete,
    alertType,
    setAlertType,
    editAlert,
    setEditAlert,
    onFeedbackUpdate,
    editAlertValue,
    setEditAlertValue,
    spinner,
    setSpinner,
    dangour,
    setDangour,
    showOptions,
    setShowOptions,
    progress,
  } = useContext(FeedbackContext);
  return {
    shimmerEffect,
    feedback,
    onSignupSubmit,
    signupError,
    user,
    formError,
    onFeedbackSubmit,
    uniqueId,
    onLoginSubmit,
    loginError,
    formValue,
    setFormValue,
    setFeedbacks,
    onFeedbackDelete,
    alertType,
    setAlertType,
    editAlert,
    setEditAlert,
    onFeedbackUpdate,
    editAlertValue,
    setEditAlertValue,
    spinner,
    setSpinner,
    dangour,
    setDangour,
    showOptions,
    setShowOptions,
    progress,
  };
};
