export default{
    "location": {
      "name": "Cherapunji",
      "region": "Meghalaya",
      "country": "India",
      "lat": 25.3,
      "lon": 91.7,
      "tz_id": "Asia/Kolkata",
      "localtime_epoch": 1728455689,
      "localtime": "2024-10-09 12:04"
    },
    "current": {
      "last_updated_epoch": 1728455400,
      "last_updated": "2024-10-09 12:00",
      "temp_c": 21.1,
      "temp_f": 69.9,
      "is_day": 1,
      "condition": {
        "text": "Light rain shower",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
        "code": 1240
      },
      "wind_mph": 2.2,
      "wind_kph": 3.6,
      "wind_degree": 274,
      "wind_dir": "W",
      "pressure_mb": 1012,
      "pressure_in": 29.87,
      "precip_mm": 0.88,
      "precip_in": 0.03,
      "humidity": 84,
      "cloud": 75,
      "feelslike_c": 21.1,
      "feelslike_f": 69.9,
      "windchill_c": 21.1,
      "windchill_f": 69.9,
      "heatindex_c": 24.2,
      "heatindex_f": 75.6,
      "dewpoint_c": 18.3,
      "dewpoint_f": 64.9,
      "vis_km": 10,
      "vis_miles": 6,
      "uv": 4,
      "gust_mph": 3.1,
      "gust_kph": 5
    },
    "forecast": {
      "forecastday": [
        {
          "date": "2024-10-09",
          "date_epoch": 1728432000,
          "day": {
            "maxtemp_c": 23.3,
            "maxtemp_f": 74,
            "mintemp_c": 16.8,
            "mintemp_f": 62.2,
            "avgtemp_c": 19.2,
            "avgtemp_f": 66.6,
            "maxwind_mph": 3.1,
            "maxwind_kph": 5,
            "totalprecip_mm": 8.61,
            "totalprecip_in": 0.34,
            "totalsnow_cm": 0,
            "avgvis_km": 8.1,
            "avgvis_miles": 5,
            "avghumidity": 89,
            "daily_will_it_rain": 1,
            "daily_chance_of_rain": 96,
            "daily_will_it_snow": 0,
            "daily_chance_of_snow": 0,
            "condition": {
              "text": "Moderate rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/302.png",
              "code": 1189
            },
            "uv": 1.5
          },
          "astro": {
            "sunrise": "05:18 AM",
            "sunset": "05:01 PM",
            "moonrise": "11:00 AM",
            "moonset": "09:21 PM",
            "moon_phase": "Waxing Crescent",
            "moon_illumination": 32,
            "is_moon_up": 0,
            "is_sun_up": 1
          },
          "hour": [
            {
              "time_epoch": 1728412200,
              "time": "2024-10-09 00:00",
              "temp_c": 17.6,
              "temp_f": 63.7,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 2.5,
              "wind_kph": 4,
              "wind_degree": 224,
              "wind_dir": "SW",
              "pressure_mb": 1015,
              "pressure_in": 29.97,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 95,
              "cloud": 34,
              "feelslike_c": 17.6,
              "feelslike_f": 63.7,
              "windchill_c": 17.6,
              "windchill_f": 63.7,
              "heatindex_c": 17.6,
              "heatindex_f": 63.7,
              "dewpoint_c": 16.9,
              "dewpoint_f": 62.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 4.4,
              "gust_kph": 7.1,
              "uv": 0
            },
            {
              "time_epoch": 1728415800,
              "time": "2024-10-09 01:00",
              "temp_c": 17.5,
              "temp_f": 63.5,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 2.2,
              "wind_kph": 3.6,
              "wind_degree": 228,
              "wind_dir": "SW",
              "pressure_mb": 1014,
              "pressure_in": 29.95,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 95,
              "cloud": 28,
              "feelslike_c": 17.5,
              "feelslike_f": 63.5,
              "windchill_c": 17.5,
              "windchill_f": 63.5,
              "heatindex_c": 17.5,
              "heatindex_f": 63.5,
              "dewpoint_c": 16.7,
              "dewpoint_f": 62,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 4,
              "gust_kph": 6.5,
              "uv": 0
            },
            {
              "time_epoch": 1728419400,
              "time": "2024-10-09 02:00",
              "temp_c": 17.4,
              "temp_f": 63.3,
              "is_day": 0,
              "condition": {
                "text": "Clear ",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 2.2,
              "wind_kph": 3.6,
              "wind_degree": 226,
              "wind_dir": "SW",
              "pressure_mb": 1014,
              "pressure_in": 29.95,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 94,
              "cloud": 24,
              "feelslike_c": 17.4,
              "feelslike_f": 63.3,
              "windchill_c": 17.4,
              "windchill_f": 63.3,
              "heatindex_c": 17.4,
              "heatindex_f": 63.3,
              "dewpoint_c": 16.4,
              "dewpoint_f": 61.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 4,
              "gust_kph": 6.5,
              "uv": 0
            },
            {
              "time_epoch": 1728423000,
              "time": "2024-10-09 03:00",
              "temp_c": 17.5,
              "temp_f": 63.5,
              "is_day": 0,
              "condition": {
                "text": "Clear ",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 1.8,
              "wind_kph": 2.9,
              "wind_degree": 226,
              "wind_dir": "SW",
              "pressure_mb": 1014,
              "pressure_in": 29.94,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 93,
              "cloud": 22,
              "feelslike_c": 17.5,
              "feelslike_f": 63.5,
              "windchill_c": 17.5,
              "windchill_f": 63.5,
              "heatindex_c": 17.5,
              "heatindex_f": 63.5,
              "dewpoint_c": 16.4,
              "dewpoint_f": 61.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 3.2,
              "gust_kph": 5.1,
              "uv": 0
            },
            {
              "time_epoch": 1728426600,
              "time": "2024-10-09 04:00",
              "temp_c": 17.6,
              "temp_f": 63.7,
              "is_day": 0,
              "condition": {
                "text": "Clear ",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 1.3,
              "wind_kph": 2.2,
              "wind_degree": 229,
              "wind_dir": "SW",
              "pressure_mb": 1014,
              "pressure_in": 29.95,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 93,
              "cloud": 20,
              "feelslike_c": 17.6,
              "feelslike_f": 63.7,
              "windchill_c": 17.6,
              "windchill_f": 63.7,
              "heatindex_c": 17.6,
              "heatindex_f": 63.7,
              "dewpoint_c": 16.5,
              "dewpoint_f": 61.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 2.3,
              "gust_kph": 3.7,
              "uv": 0
            },
            {
              "time_epoch": 1728430200,
              "time": "2024-10-09 05:00",
              "temp_c": 17.6,
              "temp_f": 63.7,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 0.9,
              "wind_kph": 1.4,
              "wind_degree": 231,
              "wind_dir": "SW",
              "pressure_mb": 1015,
              "pressure_in": 29.97,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 93,
              "cloud": 21,
              "feelslike_c": 17.6,
              "feelslike_f": 63.7,
              "windchill_c": 17.6,
              "windchill_f": 63.7,
              "heatindex_c": 17.6,
              "heatindex_f": 63.7,
              "dewpoint_c": 16.5,
              "dewpoint_f": 61.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 1.5,
              "gust_kph": 2.4,
              "uv": 0
            },
            {
              "time_epoch": 1728433800,
              "time": "2024-10-09 06:00",
              "temp_c": 19.7,
              "temp_f": 67.5,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 0.2,
              "wind_kph": 0.4,
              "wind_degree": 279,
              "wind_dir": "W",
              "pressure_mb": 1015,
              "pressure_in": 29.98,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 90,
              "cloud": 20,
              "feelslike_c": 19.7,
              "feelslike_f": 67.5,
              "windchill_c": 19.7,
              "windchill_f": 67.5,
              "heatindex_c": 19.7,
              "heatindex_f": 67.5,
              "dewpoint_c": 18.1,
              "dewpoint_f": 64.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 0.3,
              "gust_kph": 0.4,
              "uv": 0.4
            },
            {
              "time_epoch": 1728437400,
              "time": "2024-10-09 07:00",
              "temp_c": 21.8,
              "temp_f": 71.2,
              "is_day": 1,
              "condition": {
                "text": "Partly Cloudy ",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 0.9,
              "wind_kph": 1.4,
              "wind_degree": 40,
              "wind_dir": "NE",
              "pressure_mb": 1015,
              "pressure_in": 29.99,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 82,
              "cloud": 44,
              "feelslike_c": 21.8,
              "feelslike_f": 71.2,
              "windchill_c": 21.8,
              "windchill_f": 71.2,
              "heatindex_c": 24.4,
              "heatindex_f": 76,
              "dewpoint_c": 18.6,
              "dewpoint_f": 65.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 1,
              "gust_kph": 1.7,
              "uv": 1.5
            },
            {
              "time_epoch": 1728441000,
              "time": "2024-10-09 08:00",
              "temp_c": 21.3,
              "temp_f": 70.3,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain nearby",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 1.1,
              "wind_kph": 1.8,
              "wind_degree": 55,
              "wind_dir": "NE",
              "pressure_mb": 1016,
              "pressure_in": 29.99,
              "precip_mm": 0.12,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 73,
              "cloud": 86,
              "feelslike_c": 21.3,
              "feelslike_f": 70.3,
              "windchill_c": 21.3,
              "windchill_f": 70.3,
              "heatindex_c": 24.4,
              "heatindex_f": 75.9,
              "dewpoint_c": 16.3,
              "dewpoint_f": 61.4,
              "will_it_rain": 1,
              "chance_of_rain": 100,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 1.3,
              "gust_kph": 2.1,
              "uv": 3.6
            },
            {
              "time_epoch": 1728444600,
              "time": "2024-10-09 09:00",
              "temp_c": 22.9,
              "temp_f": 73.2,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain nearby",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 0.9,
              "wind_kph": 1.4,
              "wind_degree": 61,
              "wind_dir": "ENE",
              "pressure_mb": 1015,
              "pressure_in": 29.97,
              "precip_mm": 0.25,
              "precip_in": 0.01,
              "snow_cm": 0,
              "humidity": 66,
              "cloud": 80,
              "feelslike_c": 24.9,
              "feelslike_f": 76.9,
              "windchill_c": 22.9,
              "windchill_f": 73.2,
              "heatindex_c": 24.9,
              "heatindex_f": 76.9,
              "dewpoint_c": 16.3,
              "dewpoint_f": 61.4,
              "will_it_rain": 1,
              "chance_of_rain": 100,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 1,
              "gust_kph": 1.7,
              "uv": 6
            },
            {
              "time_epoch": 1728448200,
              "time": "2024-10-09 10:00",
              "temp_c": 23.3,
              "temp_f": 74,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain nearby",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 0.4,
              "wind_kph": 0.7,
              "wind_degree": 34,
              "wind_dir": "NE",
              "pressure_mb": 1014,
              "pressure_in": 29.93,
              "precip_mm": 0.26,
              "precip_in": 0.01,
              "snow_cm": 0,
              "humidity": 65,
              "cloud": 75,
              "feelslike_c": 25.2,
              "feelslike_f": 77.3,
              "windchill_c": 23.4,
              "windchill_f": 74,
              "heatindex_c": 25.2,
              "heatindex_f": 77.3,
              "dewpoint_c": 16.4,
              "dewpoint_f": 61.5,
              "will_it_rain": 1,
              "chance_of_rain": 100,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 0.5,
              "gust_kph": 0.8,
              "uv": 6.6
            },
            {
              "time_epoch": 1728451800,
              "time": "2024-10-09 11:00",
              "temp_c": 22.2,
              "temp_f": 72,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain nearby",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 0.9,
              "wind_kph": 1.4,
              "wind_degree": 295,
              "wind_dir": "WNW",
              "pressure_mb": 1012,
              "pressure_in": 29.9,
              "precip_mm": 1,
              "precip_in": 0.04,
              "snow_cm": 0,
              "humidity": 73,
              "cloud": 74,
              "feelslike_c": 24.6,
              "feelslike_f": 76.3,
              "windchill_c": 22.2,
              "windchill_f": 72,
              "heatindex_c": 24.6,
              "heatindex_f": 76.3,
              "dewpoint_c": 17.2,
              "dewpoint_f": 63,
              "will_it_rain": 1,
              "chance_of_rain": 100,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 1.3,
              "gust_kph": 2,
              "uv": 4.6
            },
            {
              "time_epoch": 1728455400,
              "time": "2024-10-09 12:00",
              "temp_c": 21.1,
              "temp_f": 69.9,
              "is_day": 1,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                "code": 1240
              },
              "wind_mph": 2.2,
              "wind_kph": 3.6,
              "wind_degree": 274,
              "wind_dir": "W",
              "pressure_mb": 1012,
              "pressure_in": 29.87,
              "precip_mm": 0.88,
              "precip_in": 0.03,
              "snow_cm": 0,
              "humidity": 84,
              "cloud": 75,
              "feelslike_c": 21.1,
              "feelslike_f": 69.9,
              "windchill_c": 21.1,
              "windchill_f": 69.9,
              "heatindex_c": 24.2,
              "heatindex_f": 75.6,
              "dewpoint_c": 18.3,
              "dewpoint_f": 64.9,
              "will_it_rain": 1,
              "chance_of_rain": 100,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 3.1,
              "gust_kph": 5,
              "uv": 4
            },
            {
              "time_epoch": 1728459000,
              "time": "2024-10-09 13:00",
              "temp_c": 20.8,
              "temp_f": 69.4,
              "is_day": 1,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                "code": 1240
              },
              "wind_mph": 2.5,
              "wind_kph": 4,
              "wind_degree": 279,
              "wind_dir": "W",
              "pressure_mb": 1011,
              "pressure_in": 29.85,
              "precip_mm": 1.77,
              "precip_in": 0.07,
              "snow_cm": 0,
              "humidity": 88,
              "cloud": 58,
              "feelslike_c": 20.8,
              "feelslike_f": 69.4,
              "windchill_c": 20.8,
              "windchill_f": 69.4,
              "heatindex_c": 20.8,
              "heatindex_f": 69.4,
              "dewpoint_c": 18.7,
              "dewpoint_f": 65.7,
              "will_it_rain": 1,
              "chance_of_rain": 100,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 4,
              "gust_kph": 6.4,
              "uv": 4.8
            },
            {
              "time_epoch": 1728462600,
              "time": "2024-10-09 14:00",
              "temp_c": 20.1,
              "temp_f": 68.2,
              "is_day": 1,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                "code": 1240
              },
              "wind_mph": 2.5,
              "wind_kph": 4,
              "wind_degree": 266,
              "wind_dir": "W",
              "pressure_mb": 1010,
              "pressure_in": 29.83,
              "precip_mm": 1.05,
              "precip_in": 0.04,
              "snow_cm": 0,
              "humidity": 90,
              "cloud": 86,
              "feelslike_c": 20.1,
              "feelslike_f": 68.2,
              "windchill_c": 20.1,
              "windchill_f": 68.2,
              "heatindex_c": 20.1,
              "heatindex_f": 68.2,
              "dewpoint_c": 18.5,
              "dewpoint_f": 65.2,
              "will_it_rain": 1,
              "chance_of_rain": 100,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 4.5,
              "gust_kph": 7.2,
              "uv": 2.8
            },
            {
              "time_epoch": 1728466200,
              "time": "2024-10-09 15:00",
              "temp_c": 19.2,
              "temp_f": 66.5,
              "is_day": 1,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                "code": 1240
              },
              "wind_mph": 2.2,
              "wind_kph": 3.6,
              "wind_degree": 271,
              "wind_dir": "W",
              "pressure_mb": 1010,
              "pressure_in": 29.84,
              "precip_mm": 1.36,
              "precip_in": 0.05,
              "snow_cm": 0,
              "humidity": 95,
              "cloud": 58,
              "feelslike_c": 19.2,
              "feelslike_f": 66.5,
              "windchill_c": 19.2,
              "windchill_f": 66.5,
              "heatindex_c": 19.2,
              "heatindex_f": 66.5,
              "dewpoint_c": 18.4,
              "dewpoint_f": 65,
              "will_it_rain": 1,
              "chance_of_rain": 100,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 4.3,
              "gust_kph": 6.9,
              "uv": 1
            },
            {
              "time_epoch": 1728469800,
              "time": "2024-10-09 16:00",
              "temp_c": 18.4,
              "temp_f": 65.1,
              "is_day": 1,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                "code": 1240
              },
              "wind_mph": 2.2,
              "wind_kph": 3.6,
              "wind_degree": 253,
              "wind_dir": "WSW",
              "pressure_mb": 1011,
              "pressure_in": 29.85,
              "precip_mm": 0.55,
              "precip_in": 0.02,
              "snow_cm": 0,
              "humidity": 96,
              "cloud": 54,
              "feelslike_c": 18.4,
              "feelslike_f": 65.1,
              "windchill_c": 18.4,
              "windchill_f": 65.1,
              "heatindex_c": 18.4,
              "heatindex_f": 65.1,
              "dewpoint_c": 17.8,
              "dewpoint_f": 64,
              "will_it_rain": 1,
              "chance_of_rain": 100,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 4.5,
              "gust_kph": 7.3,
              "uv": 0.2
            },
            {
              "time_epoch": 1728473400,
              "time": "2024-10-09 17:00",
              "temp_c": 17.4,
              "temp_f": 63.3,
              "is_day": 0,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
                "code": 1240
              },
              "wind_mph": 2.2,
              "wind_kph": 3.6,
              "wind_degree": 213,
              "wind_dir": "SSW",
              "pressure_mb": 1011,
              "pressure_in": 29.86,
              "precip_mm": 0.38,
              "precip_in": 0.02,
              "snow_cm": 0,
              "humidity": 97,
              "cloud": 61,
              "feelslike_c": 17.4,
              "feelslike_f": 63.3,
              "windchill_c": 17.4,
              "windchill_f": 63.3,
              "heatindex_c": 17.4,
              "heatindex_f": 63.3,
              "dewpoint_c": 16.9,
              "dewpoint_f": 62.5,
              "will_it_rain": 1,
              "chance_of_rain": 100,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 4.7,
              "gust_kph": 7.5,
              "uv": 0
            },
            {
              "time_epoch": 1728477000,
              "time": "2024-10-09 18:00",
              "temp_c": 16.8,
              "temp_f": 62.2,
              "is_day": 0,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
                "code": 1240
              },
              "wind_mph": 3.1,
              "wind_kph": 5,
              "wind_degree": 228,
              "wind_dir": "SW",
              "pressure_mb": 1012,
              "pressure_in": 29.9,
              "precip_mm": 0.5,
              "precip_in": 0.02,
              "snow_cm": 0,
              "humidity": 98,
              "cloud": 69,
              "feelslike_c": 16.8,
              "feelslike_f": 62.2,
              "windchill_c": 16.8,
              "windchill_f": 62.2,
              "heatindex_c": 16.8,
              "heatindex_f": 62.2,
              "dewpoint_c": 16.5,
              "dewpoint_f": 61.6,
              "will_it_rain": 1,
              "chance_of_rain": 100,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 6.6,
              "gust_kph": 10.6,
              "uv": 0
            },
            {
              "time_epoch": 1728480600,
              "time": "2024-10-09 19:00",
              "temp_c": 17.8,
              "temp_f": 64,
              "is_day": 0,
              "condition": {
                "text": "Fog",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/248.png",
                "code": 1135
              },
              "wind_mph": 2.5,
              "wind_kph": 4,
              "wind_degree": 220,
              "wind_dir": "SW",
              "pressure_mb": 1013,
              "pressure_in": 29.92,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 97,
              "cloud": 100,
              "feelslike_c": 17.8,
              "feelslike_f": 64,
              "windchill_c": 17.8,
              "windchill_f": 64,
              "heatindex_c": 17.8,
              "heatindex_f": 64,
              "dewpoint_c": 17.4,
              "dewpoint_f": 63.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 0,
              "vis_miles": 0,
              "gust_mph": 4.6,
              "gust_kph": 7.4,
              "uv": 0
            },
            {
              "time_epoch": 1728484200,
              "time": "2024-10-09 20:00",
              "temp_c": 18,
              "temp_f": 64.4,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 2,
              "wind_kph": 3.2,
              "wind_degree": 223,
              "wind_dir": "SW",
              "pressure_mb": 1013,
              "pressure_in": 29.92,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 96,
              "cloud": 46,
              "feelslike_c": 18,
              "feelslike_f": 64.4,
              "windchill_c": 18,
              "windchill_f": 64.4,
              "heatindex_c": 18,
              "heatindex_f": 64.4,
              "dewpoint_c": 17.4,
              "dewpoint_f": 63.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 3.7,
              "gust_kph": 6,
              "uv": 0
            },
            {
              "time_epoch": 1728487800,
              "time": "2024-10-09 21:00",
              "temp_c": 18.3,
              "temp_f": 64.9,
              "is_day": 0,
              "condition": {
                "text": "Patchy rain nearby",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                "code": 1063
              },
              "wind_mph": 2.2,
              "wind_kph": 3.6,
              "wind_degree": 228,
              "wind_dir": "SW",
              "pressure_mb": 1013,
              "pressure_in": 29.93,
              "precip_mm": 0.38,
              "precip_in": 0.02,
              "snow_cm": 0,
              "humidity": 95,
              "cloud": 79,
              "feelslike_c": 18.3,
              "feelslike_f": 64.9,
              "windchill_c": 18.3,
              "windchill_f": 64.9,
              "heatindex_c": 18.3,
              "heatindex_f": 64.9,
              "dewpoint_c": 17.5,
              "dewpoint_f": 63.5,
              "will_it_rain": 1,
              "chance_of_rain": 100,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 4,
              "gust_kph": 6.5,
              "uv": 0
            },
            {
              "time_epoch": 1728491400,
              "time": "2024-10-09 22:00",
              "temp_c": 18.6,
              "temp_f": 65.4,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 2.5,
              "wind_kph": 4,
              "wind_degree": 229,
              "wind_dir": "SW",
              "pressure_mb": 1013,
              "pressure_in": 29.92,
              "precip_mm": 0.1,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 94,
              "cloud": 89,
              "feelslike_c": 18.6,
              "feelslike_f": 65.4,
              "windchill_c": 18.6,
              "windchill_f": 65.4,
              "heatindex_c": 18.6,
              "heatindex_f": 65.4,
              "dewpoint_c": 17.6,
              "dewpoint_f": 63.8,
              "will_it_rain": 1,
              "chance_of_rain": 100,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 4.2,
              "gust_kph": 6.7,
              "uv": 0
            },
            {
              "time_epoch": 1728495000,
              "time": "2024-10-09 23:00",
              "temp_c": 18.6,
              "temp_f": 65.4,
              "is_day": 0,
              "condition": {
                "text": "Partly Cloudy ",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 2.2,
              "wind_kph": 3.6,
              "wind_degree": 231,
              "wind_dir": "SW",
              "pressure_mb": 1013,
              "pressure_in": 29.91,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 94,
              "cloud": 27,
              "feelslike_c": 18.6,
              "feelslike_f": 65.4,
              "windchill_c": 18.6,
              "windchill_f": 65.4,
              "heatindex_c": 18.6,
              "heatindex_f": 65.4,
              "dewpoint_c": 17.5,
              "dewpoint_f": 63.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 3.7,
              "gust_kph": 6,
              "uv": 0
            }
          ]
        },
        {
          "date": "2024-10-10",
          "date_epoch": 1728518400,
          "day": {
            "maxtemp_c": 21.3,
            "maxtemp_f": 70.4,
            "mintemp_c": 17.1,
            "mintemp_f": 62.9,
            "avgtemp_c": 18.9,
            "avgtemp_f": 66,
            "maxwind_mph": 4,
            "maxwind_kph": 6.5,
            "totalprecip_mm": 8.51,
            "totalprecip_in": 0.33,
            "totalsnow_cm": 0,
            "avgvis_km": 6.9,
            "avgvis_miles": 4,
            "avghumidity": 92,
            "daily_will_it_rain": 1,
            "daily_chance_of_rain": 89,
            "daily_will_it_snow": 0,
            "daily_chance_of_snow": 0,
            "condition": {
              "text": "Moderate rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/302.png",
              "code": 1189
            },
            "uv": 1.4
          },
          "astro": {
            "sunrise": "05:19 AM",
            "sunset": "05:00 PM",
            "moonrise": "11:56 AM",
            "moonset": "10:20 PM",
            "moon_phase": "First Quarter",
            "moon_illumination": 42,
            "is_moon_up": 0,
            "is_sun_up": 1
          },
          "hour": [
            {
              "time_epoch": 1728498600,
              "time": "2024-10-10 00:00",
              "temp_c": 18.4,
              "temp_f": 65.1,
              "is_day": 0,
              "condition": {
                "text": "Partly Cloudy ",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 2,
              "wind_kph": 3.2,
              "wind_degree": 233,
              "wind_dir": "SW",
              "pressure_mb": 1012,
              "pressure_in": 29.9,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 94,
              "cloud": 27,
              "feelslike_c": 18.4,
              "feelslike_f": 65,
              "windchill_c": 18.4,
              "windchill_f": 65,
              "heatindex_c": 18.4,
              "heatindex_f": 65,
              "dewpoint_c": 17.3,
              "dewpoint_f": 63.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 3.4,
              "gust_kph": 5.5,
              "uv": 0
            },
            {
              "time_epoch": 1728502200,
              "time": "2024-10-10 01:00",
              "temp_c": 18.3,
              "temp_f": 64.9,
              "is_day": 0,
              "condition": {
                "text": "Clear ",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 2,
              "wind_kph": 3.2,
              "wind_degree": 233,
              "wind_dir": "SW",
              "pressure_mb": 1012,
              "pressure_in": 29.89,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 94,
              "cloud": 24,
              "feelslike_c": 18.3,
              "feelslike_f": 64.9,
              "windchill_c": 18.3,
              "windchill_f": 64.9,
              "heatindex_c": 18.3,
              "heatindex_f": 64.9,
              "dewpoint_c": 17.2,
              "dewpoint_f": 63,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 3.4,
              "gust_kph": 5.5,
              "uv": 0
            },
            {
              "time_epoch": 1728505800,
              "time": "2024-10-10 02:00",
              "temp_c": 18.2,
              "temp_f": 64.8,
              "is_day": 0,
              "condition": {
                "text": "Clear ",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 1.8,
              "wind_kph": 2.9,
              "wind_degree": 218,
              "wind_dir": "SW",
              "pressure_mb": 1012,
              "pressure_in": 29.88,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 93,
              "cloud": 24,
              "feelslike_c": 18.3,
              "feelslike_f": 64.9,
              "windchill_c": 18.3,
              "windchill_f": 64.9,
              "heatindex_c": 18.3,
              "heatindex_f": 64.9,
              "dewpoint_c": 17.2,
              "dewpoint_f": 62.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 3,
              "gust_kph": 4.9,
              "uv": 0
            },
            {
              "time_epoch": 1728509400,
              "time": "2024-10-10 03:00",
              "temp_c": 18,
              "temp_f": 64.4,
              "is_day": 0,
              "condition": {
                "text": "Clear ",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 1.8,
              "wind_kph": 2.9,
              "wind_degree": 218,
              "wind_dir": "SW",
              "pressure_mb": 1012,
              "pressure_in": 29.88,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 93,
              "cloud": 24,
              "feelslike_c": 18,
              "feelslike_f": 64.3,
              "windchill_c": 18,
              "windchill_f": 64.3,
              "heatindex_c": 18,
              "heatindex_f": 64.3,
              "dewpoint_c": 16.9,
              "dewpoint_f": 62.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 3.2,
              "gust_kph": 5.1,
              "uv": 0
            },
            {
              "time_epoch": 1728513000,
              "time": "2024-10-10 04:00",
              "temp_c": 17.7,
              "temp_f": 63.9,
              "is_day": 0,
              "condition": {
                "text": "Patchy rain nearby",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                "code": 1063
              },
              "wind_mph": 2,
              "wind_kph": 3.2,
              "wind_degree": 211,
              "wind_dir": "SSW",
              "pressure_mb": 1012,
              "pressure_in": 29.89,
              "precip_mm": 0.09,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 93,
              "cloud": 84,
              "feelslike_c": 17.7,
              "feelslike_f": 63.9,
              "windchill_c": 17.7,
              "windchill_f": 63.9,
              "heatindex_c": 17.7,
              "heatindex_f": 63.9,
              "dewpoint_c": 16.6,
              "dewpoint_f": 61.9,
              "will_it_rain": 1,
              "chance_of_rain": 100,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 3.6,
              "gust_kph": 5.9,
              "uv": 0
            },
            {
              "time_epoch": 1728516600,
              "time": "2024-10-10 05:00",
              "temp_c": 17.7,
              "temp_f": 63.9,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain nearby",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 2.2,
              "wind_kph": 3.6,
              "wind_degree": 213,
              "wind_dir": "SSW",
              "pressure_mb": 1013,
              "pressure_in": 29.91,
              "precip_mm": 0.04,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 93,
              "cloud": 82,
              "feelslike_c": 17.7,
              "feelslike_f": 63.9,
              "windchill_c": 17.7,
              "windchill_f": 63.9,
              "heatindex_c": 17.7,
              "heatindex_f": 63.9,
              "dewpoint_c": 16.6,
              "dewpoint_f": 61.9,
              "will_it_rain": 1,
              "chance_of_rain": 72,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 4,
              "gust_kph": 6.5,
              "uv": 0
            },
            {
              "time_epoch": 1728520200,
              "time": "2024-10-10 06:00",
              "temp_c": 20.1,
              "temp_f": 68.1,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain nearby",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 2.2,
              "wind_kph": 3.6,
              "wind_degree": 206,
              "wind_dir": "SSW",
              "pressure_mb": 1013,
              "pressure_in": 29.92,
              "precip_mm": 0.09,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 91,
              "cloud": 81,
              "feelslike_c": 20.1,
              "feelslike_f": 68.1,
              "windchill_c": 20.1,
              "windchill_f": 68.1,
              "heatindex_c": 20.1,
              "heatindex_f": 68.1,
              "dewpoint_c": 18.6,
              "dewpoint_f": 65.5,
              "will_it_rain": 1,
              "chance_of_rain": 100,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 2.7,
              "gust_kph": 4.3,
              "uv": 0.3
            },
            {
              "time_epoch": 1728523800,
              "time": "2024-10-10 07:00",
              "temp_c": 21.3,
              "temp_f": 70.4,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain nearby",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 2.2,
              "wind_kph": 3.6,
              "wind_degree": 203,
              "wind_dir": "SSW",
              "pressure_mb": 1014,
              "pressure_in": 29.93,
              "precip_mm": 0.35,
              "precip_in": 0.01,
              "snow_cm": 0,
              "humidity": 85,
              "cloud": 80,
              "feelslike_c": 21.4,
              "feelslike_f": 70.4,
              "windchill_c": 21.4,
              "windchill_f": 70.4,
              "heatindex_c": 24.3,
              "heatindex_f": 75.7,
              "dewpoint_c": 18.7,
              "dewpoint_f": 65.7,
              "will_it_rain": 1,
              "chance_of_rain": 100,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 2.6,
              "gust_kph": 4.2,
              "uv": 1.4
            },
            {
              "time_epoch": 1728527400,
              "time": "2024-10-10 08:00",
              "temp_c": 20.4,
              "temp_f": 68.7,
              "is_day": 1,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                "code": 1240
              },
              "wind_mph": 2.2,
              "wind_kph": 3.6,
              "wind_degree": 219,
              "wind_dir": "SW",
              "pressure_mb": 1014,
              "pressure_in": 29.94,
              "precip_mm": 1.07,
              "precip_in": 0.04,
              "snow_cm": 0,
              "humidity": 82,
              "cloud": 54,
              "feelslike_c": 20.4,
              "feelslike_f": 68.7,
              "windchill_c": 20.4,
              "windchill_f": 68.7,
              "heatindex_c": 20.4,
              "heatindex_f": 68.7,
              "dewpoint_c": 17.3,
              "dewpoint_f": 63.1,
              "will_it_rain": 1,
              "chance_of_rain": 100,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 3.1,
              "gust_kph": 4.9,
              "uv": 3.4
            },
            {
              "time_epoch": 1728531000,
              "time": "2024-10-10 09:00",
              "temp_c": 20.6,
              "temp_f": 69.1,
              "is_day": 1,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                "code": 1240
              },
              "wind_mph": 2.2,
              "wind_kph": 3.6,
              "wind_degree": 240,
              "wind_dir": "WSW",
              "pressure_mb": 1014,
              "pressure_in": 29.93,
              "precip_mm": 1.05,
              "precip_in": 0.04,
              "snow_cm": 0,
              "humidity": 85,
              "cloud": 52,
              "feelslike_c": 20.6,
              "feelslike_f": 69.1,
              "windchill_c": 20.6,
              "windchill_f": 69.1,
              "heatindex_c": 20.6,
              "heatindex_f": 69.1,
              "dewpoint_c": 18,
              "dewpoint_f": 64.5,
              "will_it_rain": 1,
              "chance_of_rain": 100,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 3.2,
              "gust_kph": 5.1,
              "uv": 5.8
            },
            {
              "time_epoch": 1728534600,
              "time": "2024-10-10 10:00",
              "temp_c": 20.6,
              "temp_f": 69,
              "is_day": 1,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                "code": 1240
              },
              "wind_mph": 2.7,
              "wind_kph": 4.3,
              "wind_degree": 248,
              "wind_dir": "WSW",
              "pressure_mb": 1013,
              "pressure_in": 29.91,
              "precip_mm": 1.38,
              "precip_in": 0.05,
              "snow_cm": 0,
              "humidity": 87,
              "cloud": 76,
              "feelslike_c": 20.6,
              "feelslike_f": 69,
              "windchill_c": 20.6,
              "windchill_f": 69,
              "heatindex_c": 20.6,
              "heatindex_f": 69,
              "dewpoint_c": 18.4,
              "dewpoint_f": 65.1,
              "will_it_rain": 1,
              "chance_of_rain": 100,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 4.3,
              "gust_kph": 7,
              "uv": 6.1
            },
            {
              "time_epoch": 1728538200,
              "time": "2024-10-10 11:00",
              "temp_c": 20.4,
              "temp_f": 68.8,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain nearby",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 3.1,
              "wind_kph": 5,
              "wind_degree": 248,
              "wind_dir": "WSW",
              "pressure_mb": 1012,
              "pressure_in": 29.88,
              "precip_mm": 1.25,
              "precip_in": 0.05,
              "snow_cm": 0,
              "humidity": 88,
              "cloud": 70,
              "feelslike_c": 20.5,
              "feelslike_f": 68.8,
              "windchill_c": 20.5,
              "windchill_f": 68.8,
              "heatindex_c": 20.5,
              "heatindex_f": 68.8,
              "dewpoint_c": 18.5,
              "dewpoint_f": 65.2,
              "will_it_rain": 1,
              "chance_of_rain": 100,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 5.5,
              "gust_kph": 8.9,
              "uv": 4.8
            },
            {
              "time_epoch": 1728541800,
              "time": "2024-10-10 12:00",
              "temp_c": 20.5,
              "temp_f": 68.9,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain nearby",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 4,
              "wind_kph": 6.5,
              "wind_degree": 242,
              "wind_dir": "WSW",
              "pressure_mb": 1011,
              "pressure_in": 29.85,
              "precip_mm": 1,
              "precip_in": 0.04,
              "snow_cm": 0,
              "humidity": 89,
              "cloud": 81,
              "feelslike_c": 20.5,
              "feelslike_f": 68.8,
              "windchill_c": 20.5,
              "windchill_f": 68.8,
              "heatindex_c": 20.5,
              "heatindex_f": 68.8,
              "dewpoint_c": 18.7,
              "dewpoint_f": 65.6,
              "will_it_rain": 1,
              "chance_of_rain": 100,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 5.7,
              "gust_kph": 9.3,
              "uv": 5.3
            },
            {
              "time_epoch": 1728545400,
              "time": "2024-10-10 13:00",
              "temp_c": 20.5,
              "temp_f": 68.8,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain nearby",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 3.6,
              "wind_kph": 5.8,
              "wind_degree": 241,
              "wind_dir": "WSW",
              "pressure_mb": 1010,
              "pressure_in": 29.82,
              "precip_mm": 0.66,
              "precip_in": 0.03,
              "snow_cm": 0,
              "humidity": 89,
              "cloud": 86,
              "feelslike_c": 20.5,
              "feelslike_f": 68.8,
              "windchill_c": 20.5,
              "windchill_f": 68.8,
              "heatindex_c": 20.5,
              "heatindex_f": 68.8,
              "dewpoint_c": 18.6,
              "dewpoint_f": 65.6,
              "will_it_rain": 1,
              "chance_of_rain": 100,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 5.4,
              "gust_kph": 8.7,
              "uv": 5.2
            },
            {
              "time_epoch": 1728549000,
              "time": "2024-10-10 14:00",
              "temp_c": 20.4,
              "temp_f": 68.7,
              "is_day": 1,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                "code": 1240
              },
              "wind_mph": 3.1,
              "wind_kph": 5,
              "wind_degree": 239,
              "wind_dir": "WSW",
              "pressure_mb": 1009,
              "pressure_in": 29.81,
              "precip_mm": 0.79,
              "precip_in": 0.03,
              "snow_cm": 0,
              "humidity": 89,
              "cloud": 89,
              "feelslike_c": 20.4,
              "feelslike_f": 68.7,
              "windchill_c": 20.4,
              "windchill_f": 68.7,
              "heatindex_c": 20.4,
              "heatindex_f": 68.7,
              "dewpoint_c": 18.6,
              "dewpoint_f": 65.4,
              "will_it_rain": 1,
              "chance_of_rain": 100,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 5,
              "gust_kph": 8,
              "uv": 2.5
            },
            {
              "time_epoch": 1728552600,
              "time": "2024-10-10 15:00",
              "temp_c": 19.5,
              "temp_f": 67,
              "is_day": 1,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                "code": 1240
              },
              "wind_mph": 3.1,
              "wind_kph": 5,
              "wind_degree": 235,
              "wind_dir": "SW",
              "pressure_mb": 1010,
              "pressure_in": 29.82,
              "precip_mm": 0.64,
              "precip_in": 0.03,
              "snow_cm": 0,
              "humidity": 94,
              "cloud": 54,
              "feelslike_c": 19.5,
              "feelslike_f": 67,
              "windchill_c": 19.5,
              "windchill_f": 67,
              "heatindex_c": 19.5,
              "heatindex_f": 67,
              "dewpoint_c": 18.5,
              "dewpoint_f": 65.3,
              "will_it_rain": 1,
              "chance_of_rain": 100,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 5.3,
              "gust_kph": 8.5,
              "uv": 0.9
            },
            {
              "time_epoch": 1728556200,
              "time": "2024-10-10 16:00",
              "temp_c": 18.3,
              "temp_f": 64.9,
              "is_day": 1,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/143.png",
                "code": 1030
              },
              "wind_mph": 2.7,
              "wind_kph": 4.3,
              "wind_degree": 226,
              "wind_dir": "SW",
              "pressure_mb": 1010,
              "pressure_in": 29.83,
              "precip_mm": 0.1,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 97,
              "cloud": 66,
              "feelslike_c": 18.3,
              "feelslike_f": 64.9,
              "windchill_c": 18.3,
              "windchill_f": 64.9,
              "heatindex_c": 18.3,
              "heatindex_f": 64.9,
              "dewpoint_c": 17.8,
              "dewpoint_f": 64,
              "will_it_rain": 1,
              "chance_of_rain": 100,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 4.9,
              "gust_kph": 7.8,
              "uv": 0.2
            },
            {
              "time_epoch": 1728559800,
              "time": "2024-10-10 17:00",
              "temp_c": 17.1,
              "temp_f": 62.9,
              "is_day": 0,
              "condition": {
                "text": "Fog",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/248.png",
                "code": 1135
              },
              "wind_mph": 2.7,
              "wind_kph": 4.3,
              "wind_degree": 226,
              "wind_dir": "SW",
              "pressure_mb": 1011,
              "pressure_in": 29.85,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 98,
              "cloud": 100,
              "feelslike_c": 17.1,
              "feelslike_f": 62.9,
              "windchill_c": 17.1,
              "windchill_f": 62.9,
              "heatindex_c": 17.1,
              "heatindex_f": 62.9,
              "dewpoint_c": 16.8,
              "dewpoint_f": 62.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 0,
              "vis_miles": 0,
              "gust_mph": 5.3,
              "gust_kph": 8.6,
              "uv": 0
            },
            {
              "time_epoch": 1728563400,
              "time": "2024-10-10 18:00",
              "temp_c": 18,
              "temp_f": 64.4,
              "is_day": 0,
              "condition": {
                "text": "Fog",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/248.png",
                "code": 1135
              },
              "wind_mph": 3.1,
              "wind_kph": 5,
              "wind_degree": 217,
              "wind_dir": "SW",
              "pressure_mb": 1012,
              "pressure_in": 29.88,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 97,
              "cloud": 100,
              "feelslike_c": 18,
              "feelslike_f": 64.4,
              "windchill_c": 18,
              "windchill_f": 64.4,
              "heatindex_c": 18,
              "heatindex_f": 64.4,
              "dewpoint_c": 17.6,
              "dewpoint_f": 63.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 0,
              "vis_miles": 0,
              "gust_mph": 5.3,
              "gust_kph": 8.5,
              "uv": 0
            },
            {
              "time_epoch": 1728567000,
              "time": "2024-10-10 19:00",
              "temp_c": 18,
              "temp_f": 64.3,
              "is_day": 0,
              "condition": {
                "text": "Fog",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/248.png",
                "code": 1135
              },
              "wind_mph": 2.9,
              "wind_kph": 4.7,
              "wind_degree": 216,
              "wind_dir": "SW",
              "pressure_mb": 1013,
              "pressure_in": 29.91,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 97,
              "cloud": 100,
              "feelslike_c": 18,
              "feelslike_f": 64.3,
              "windchill_c": 18,
              "windchill_f": 64.3,
              "heatindex_c": 18,
              "heatindex_f": 64.3,
              "dewpoint_c": 17.5,
              "dewpoint_f": 63.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 0,
              "vis_miles": 0,
              "gust_mph": 4.9,
              "gust_kph": 7.9,
              "uv": 0
            },
            {
              "time_epoch": 1728570600,
              "time": "2024-10-10 20:00",
              "temp_c": 17.9,
              "temp_f": 64.2,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 2.7,
              "wind_kph": 4.3,
              "wind_degree": 218,
              "wind_dir": "SW",
              "pressure_mb": 1013,
              "pressure_in": 29.92,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 97,
              "cloud": 57,
              "feelslike_c": 17.9,
              "feelslike_f": 64.1,
              "windchill_c": 17.9,
              "windchill_f": 64.1,
              "heatindex_c": 17.9,
              "heatindex_f": 64.1,
              "dewpoint_c": 17.4,
              "dewpoint_f": 63.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 4.5,
              "gust_kph": 7.3,
              "uv": 0
            },
            {
              "time_epoch": 1728574200,
              "time": "2024-10-10 21:00",
              "temp_c": 17.2,
              "temp_f": 63,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 2.7,
              "wind_kph": 4.3,
              "wind_degree": 221,
              "wind_dir": "SW",
              "pressure_mb": 1013,
              "pressure_in": 29.92,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 97,
              "cloud": 51,
              "feelslike_c": 17.2,
              "feelslike_f": 63,
              "windchill_c": 17.2,
              "windchill_f": 63,
              "heatindex_c": 17.2,
              "heatindex_f": 63,
              "dewpoint_c": 16.7,
              "dewpoint_f": 62,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 5,
              "gust_kph": 8,
              "uv": 0
            },
            {
              "time_epoch": 1728577800,
              "time": "2024-10-10 22:00",
              "temp_c": 17.3,
              "temp_f": 63.2,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 2.9,
              "wind_kph": 4.7,
              "wind_degree": 225,
              "wind_dir": "SW",
              "pressure_mb": 1013,
              "pressure_in": 29.91,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 96,
              "cloud": 44,
              "feelslike_c": 17.3,
              "feelslike_f": 63.2,
              "windchill_c": 17.3,
              "windchill_f": 63.2,
              "heatindex_c": 17.3,
              "heatindex_f": 63.2,
              "dewpoint_c": 16.7,
              "dewpoint_f": 62,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 5.3,
              "gust_kph": 8.5,
              "uv": 0
            },
            {
              "time_epoch": 1728581400,
              "time": "2024-10-10 23:00",
              "temp_c": 17.3,
              "temp_f": 63.1,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 2.9,
              "wind_kph": 4.7,
              "wind_degree": 222,
              "wind_dir": "SW",
              "pressure_mb": 1013,
              "pressure_in": 29.91,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 96,
              "cloud": 40,
              "feelslike_c": 17.3,
              "feelslike_f": 63.1,
              "windchill_c": 17.3,
              "windchill_f": 63.1,
              "heatindex_c": 17.3,
              "heatindex_f": 63.1,
              "dewpoint_c": 16.6,
              "dewpoint_f": 61.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 5.2,
              "gust_kph": 8.4,
              "uv": 0
            }
          ]
        },
        {
          "date": "2024-10-11",
          "date_epoch": 1728604800,
          "day": {
            "maxtemp_c": 23.4,
            "maxtemp_f": 74.2,
            "mintemp_c": 17,
            "mintemp_f": 62.6,
            "avgtemp_c": 19.1,
            "avgtemp_f": 66.4,
            "maxwind_mph": 3.1,
            "maxwind_kph": 5,
            "totalprecip_mm": 3.37,
            "totalprecip_in": 0.13,
            "totalsnow_cm": 0,
            "avgvis_km": 5.8,
            "avgvis_miles": 3,
            "avghumidity": 87,
            "daily_will_it_rain": 1,
            "daily_chance_of_rain": 89,
            "daily_will_it_snow": 0,
            "daily_chance_of_snow": 0,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "uv": 1.5
          },
          "astro": {
            "sunrise": "05:19 AM",
            "sunset": "04:59 PM",
            "moonrise": "12:47 PM",
            "moonset": "11:24 PM",
            "moon_phase": "Waxing Gibbous",
            "moon_illumination": 52,
            "is_moon_up": 0,
            "is_sun_up": 1
          },
          "hour": [
            {
              "time_epoch": 1728585000,
              "time": "2024-10-11 00:00",
              "temp_c": 17.3,
              "temp_f": 63.1,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 2.9,
              "wind_kph": 4.7,
              "wind_degree": 231,
              "wind_dir": "SW",
              "pressure_mb": 1012,
              "pressure_in": 29.9,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 95,
              "cloud": 34,
              "feelslike_c": 17.3,
              "feelslike_f": 63.1,
              "windchill_c": 17.3,
              "windchill_f": 63.1,
              "heatindex_c": 17.3,
              "heatindex_f": 63.1,
              "dewpoint_c": 16.5,
              "dewpoint_f": 61.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 5.2,
              "gust_kph": 8.4,
              "uv": 0
            },
            {
              "time_epoch": 1728588600,
              "time": "2024-10-11 01:00",
              "temp_c": 17.2,
              "temp_f": 62.9,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 2.9,
              "wind_kph": 4.7,
              "wind_degree": 235,
              "wind_dir": "SW",
              "pressure_mb": 1012,
              "pressure_in": 29.89,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 95,
              "cloud": 32,
              "feelslike_c": 17.2,
              "feelslike_f": 62.9,
              "windchill_c": 17.2,
              "windchill_f": 62.9,
              "heatindex_c": 17.2,
              "heatindex_f": 62.9,
              "dewpoint_c": 16.3,
              "dewpoint_f": 61.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 5.2,
              "gust_kph": 8.4,
              "uv": 0
            },
            {
              "time_epoch": 1728592200,
              "time": "2024-10-11 02:00",
              "temp_c": 17.2,
              "temp_f": 62.9,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 2.9,
              "wind_kph": 4.7,
              "wind_degree": 239,
              "wind_dir": "WSW",
              "pressure_mb": 1012,
              "pressure_in": 29.89,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 95,
              "cloud": 36,
              "feelslike_c": 17.2,
              "feelslike_f": 62.9,
              "windchill_c": 17.2,
              "windchill_f": 62.9,
              "heatindex_c": 17.2,
              "heatindex_f": 62.9,
              "dewpoint_c": 16.4,
              "dewpoint_f": 61.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 5.1,
              "gust_kph": 8.3,
              "uv": 0
            },
            {
              "time_epoch": 1728595800,
              "time": "2024-10-11 03:00",
              "temp_c": 17.2,
              "temp_f": 63,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 2.7,
              "wind_kph": 4.3,
              "wind_degree": 237,
              "wind_dir": "WSW",
              "pressure_mb": 1012,
              "pressure_in": 29.89,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 95,
              "cloud": 40,
              "feelslike_c": 17.2,
              "feelslike_f": 63,
              "windchill_c": 17.2,
              "windchill_f": 63,
              "heatindex_c": 17.2,
              "heatindex_f": 63,
              "dewpoint_c": 16.5,
              "dewpoint_f": 61.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 4.7,
              "gust_kph": 7.5,
              "uv": 0
            },
            {
              "time_epoch": 1728599400,
              "time": "2024-10-11 04:00",
              "temp_c": 17.3,
              "temp_f": 63.1,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 2.5,
              "wind_kph": 4,
              "wind_degree": 235,
              "wind_dir": "SW",
              "pressure_mb": 1012,
              "pressure_in": 29.9,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 95,
              "cloud": 39,
              "feelslike_c": 17.3,
              "feelslike_f": 63.1,
              "windchill_c": 17.3,
              "windchill_f": 63.1,
              "heatindex_c": 17.3,
              "heatindex_f": 63.1,
              "dewpoint_c": 16.5,
              "dewpoint_f": 61.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 4.3,
              "gust_kph": 6.9,
              "uv": 0
            },
            {
              "time_epoch": 1728603000,
              "time": "2024-10-11 05:00",
              "temp_c": 17.2,
              "temp_f": 63,
              "is_day": 1,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/143.png",
                "code": 1030
              },
              "wind_mph": 2.5,
              "wind_kph": 4,
              "wind_degree": 231,
              "wind_dir": "SW",
              "pressure_mb": 1013,
              "pressure_in": 29.91,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 95,
              "cloud": 34,
              "feelslike_c": 17.2,
              "feelslike_f": 63,
              "windchill_c": 17.2,
              "windchill_f": 63,
              "heatindex_c": 17.2,
              "heatindex_f": 63,
              "dewpoint_c": 16.4,
              "dewpoint_f": 61.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 4.3,
              "gust_kph": 7,
              "uv": 0
            },
            {
              "time_epoch": 1728606600,
              "time": "2024-10-11 06:00",
              "temp_c": 19.2,
              "temp_f": 66.6,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 2.2,
              "wind_kph": 3.6,
              "wind_degree": 222,
              "wind_dir": "SW",
              "pressure_mb": 1013,
              "pressure_in": 29.92,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 92,
              "cloud": 25,
              "feelslike_c": 19.2,
              "feelslike_f": 66.6,
              "windchill_c": 19.2,
              "windchill_f": 66.6,
              "heatindex_c": 19.2,
              "heatindex_f": 66.6,
              "dewpoint_c": 17.9,
              "dewpoint_f": 64.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 2.9,
              "gust_kph": 4.6,
              "uv": 0.3
            },
            {
              "time_epoch": 1728610200,
              "time": "2024-10-11 07:00",
              "temp_c": 21.8,
              "temp_f": 71.2,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain nearby",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 2.7,
              "wind_kph": 4.3,
              "wind_degree": 236,
              "wind_dir": "WSW",
              "pressure_mb": 1013,
              "pressure_in": 29.93,
              "precip_mm": 0.01,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 81,
              "cloud": 76,
              "feelslike_c": 21.8,
              "feelslike_f": 71.2,
              "windchill_c": 21.8,
              "windchill_f": 71.2,
              "heatindex_c": 24.4,
              "heatindex_f": 76,
              "dewpoint_c": 18.3,
              "dewpoint_f": 64.9,
              "will_it_rain": 0,
              "chance_of_rain": 66,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 3.1,
              "gust_kph": 5,
              "uv": 1.3
            },
            {
              "time_epoch": 1728613800,
              "time": "2024-10-11 08:00",
              "temp_c": 21.4,
              "temp_f": 70.4,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain nearby",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 2.9,
              "wind_kph": 4.7,
              "wind_degree": 254,
              "wind_dir": "WSW",
              "pressure_mb": 1013,
              "pressure_in": 29.93,
              "precip_mm": 0.02,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 69,
              "cloud": 73,
              "feelslike_c": 21.4,
              "feelslike_f": 70.4,
              "windchill_c": 21.4,
              "windchill_f": 70.4,
              "heatindex_c": 24.4,
              "heatindex_f": 76,
              "dewpoint_c": 15.5,
              "dewpoint_f": 59.9,
              "will_it_rain": 1,
              "chance_of_rain": 80,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 3.4,
              "gust_kph": 5.5,
              "uv": 3.1
            },
            {
              "time_epoch": 1728617400,
              "time": "2024-10-11 09:00",
              "temp_c": 22.6,
              "temp_f": 72.6,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain nearby",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 3.1,
              "wind_kph": 5,
              "wind_degree": 260,
              "wind_dir": "W",
              "pressure_mb": 1013,
              "pressure_in": 29.91,
              "precip_mm": 0.03,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 62,
              "cloud": 74,
              "feelslike_c": 24.8,
              "feelslike_f": 76.6,
              "windchill_c": 22.6,
              "windchill_f": 72.6,
              "heatindex_c": 24.8,
              "heatindex_f": 76.6,
              "dewpoint_c": 14.9,
              "dewpoint_f": 58.8,
              "will_it_rain": 0,
              "chance_of_rain": 67,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 3.7,
              "gust_kph": 6,
              "uv": 5.8
            },
            {
              "time_epoch": 1728621000,
              "time": "2024-10-11 10:00",
              "temp_c": 23.4,
              "temp_f": 74.2,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain nearby",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 2.9,
              "wind_kph": 4.7,
              "wind_degree": 259,
              "wind_dir": "W",
              "pressure_mb": 1012,
              "pressure_in": 29.88,
              "precip_mm": 0.03,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 58,
              "cloud": 74,
              "feelslike_c": 25.1,
              "feelslike_f": 77.2,
              "windchill_c": 23.4,
              "windchill_f": 74.2,
              "heatindex_c": 25.1,
              "heatindex_f": 77.2,
              "dewpoint_c": 14.8,
              "dewpoint_f": 58.7,
              "will_it_rain": 1,
              "chance_of_rain": 89,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 3.5,
              "gust_kph": 5.6,
              "uv": 7.1
            },
            {
              "time_epoch": 1728624600,
              "time": "2024-10-11 11:00",
              "temp_c": 22.9,
              "temp_f": 73.2,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain nearby",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 2.5,
              "wind_kph": 4,
              "wind_degree": 253,
              "wind_dir": "WSW",
              "pressure_mb": 1011,
              "pressure_in": 29.85,
              "precip_mm": 0.08,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 61,
              "cloud": 84,
              "feelslike_c": 24.9,
              "feelslike_f": 76.8,
              "windchill_c": 22.9,
              "windchill_f": 73.1,
              "heatindex_c": 24.9,
              "heatindex_f": 76.8,
              "dewpoint_c": 15.1,
              "dewpoint_f": 59.1,
              "will_it_rain": 1,
              "chance_of_rain": 100,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 3.3,
              "gust_kph": 5.4,
              "uv": 4.5
            },
            {
              "time_epoch": 1728628200,
              "time": "2024-10-11 12:00",
              "temp_c": 21.5,
              "temp_f": 70.7,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain nearby",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 2.5,
              "wind_kph": 4,
              "wind_degree": 251,
              "wind_dir": "WSW",
              "pressure_mb": 1010,
              "pressure_in": 29.84,
              "precip_mm": 0.37,
              "precip_in": 0.01,
              "snow_cm": 0,
              "humidity": 74,
              "cloud": 84,
              "feelslike_c": 21.5,
              "feelslike_f": 70.7,
              "windchill_c": 21.5,
              "windchill_f": 70.7,
              "heatindex_c": 24.4,
              "heatindex_f": 75.9,
              "dewpoint_c": 16.8,
              "dewpoint_f": 62.2,
              "will_it_rain": 1,
              "chance_of_rain": 100,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 3.7,
              "gust_kph": 6,
              "uv": 3.6
            },
            {
              "time_epoch": 1728631800,
              "time": "2024-10-11 13:00",
              "temp_c": 21.1,
              "temp_f": 69.9,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain nearby",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 2.7,
              "wind_kph": 4.3,
              "wind_degree": 263,
              "wind_dir": "W",
              "pressure_mb": 1010,
              "pressure_in": 29.82,
              "precip_mm": 0.73,
              "precip_in": 0.03,
              "snow_cm": 0,
              "humidity": 80,
              "cloud": 83,
              "feelslike_c": 21.1,
              "feelslike_f": 69.9,
              "windchill_c": 21.1,
              "windchill_f": 69.9,
              "heatindex_c": 24.3,
              "heatindex_f": 75.7,
              "dewpoint_c": 17.5,
              "dewpoint_f": 63.5,
              "will_it_rain": 1,
              "chance_of_rain": 100,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 4,
              "gust_kph": 6.4,
              "uv": 4.6
            },
            {
              "time_epoch": 1728635400,
              "time": "2024-10-11 14:00",
              "temp_c": 20.5,
              "temp_f": 68.9,
              "is_day": 1,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                "code": 1240
              },
              "wind_mph": 2.2,
              "wind_kph": 3.6,
              "wind_degree": 269,
              "wind_dir": "W",
              "pressure_mb": 1009,
              "pressure_in": 29.81,
              "precip_mm": 0.91,
              "precip_in": 0.04,
              "snow_cm": 0,
              "humidity": 85,
              "cloud": 53,
              "feelslike_c": 20.5,
              "feelslike_f": 68.9,
              "windchill_c": 20.5,
              "windchill_f": 68.9,
              "heatindex_c": 20.5,
              "heatindex_f": 68.9,
              "dewpoint_c": 18,
              "dewpoint_f": 64.3,
              "will_it_rain": 1,
              "chance_of_rain": 100,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 3.3,
              "gust_kph": 5.3,
              "uv": 2.6
            },
            {
              "time_epoch": 1728639000,
              "time": "2024-10-11 15:00",
              "temp_c": 19.1,
              "temp_f": 66.3,
              "is_day": 1,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                "code": 1240
              },
              "wind_mph": 2.5,
              "wind_kph": 4,
              "wind_degree": 250,
              "wind_dir": "WSW",
              "pressure_mb": 1010,
              "pressure_in": 29.82,
              "precip_mm": 0.65,
              "precip_in": 0.03,
              "snow_cm": 0,
              "humidity": 95,
              "cloud": 54,
              "feelslike_c": 19.1,
              "feelslike_f": 66.3,
              "windchill_c": 19.1,
              "windchill_f": 66.3,
              "heatindex_c": 19.1,
              "heatindex_f": 66.3,
              "dewpoint_c": 18.2,
              "dewpoint_f": 64.8,
              "will_it_rain": 1,
              "chance_of_rain": 100,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 3.9,
              "gust_kph": 6.3,
              "uv": 0.9
            },
            {
              "time_epoch": 1728642600,
              "time": "2024-10-11 16:00",
              "temp_c": 18.1,
              "temp_f": 64.6,
              "is_day": 1,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                "code": 1240
              },
              "wind_mph": 2.2,
              "wind_kph": 3.6,
              "wind_degree": 232,
              "wind_dir": "SW",
              "pressure_mb": 1010,
              "pressure_in": 29.83,
              "precip_mm": 0.33,
              "precip_in": 0.01,
              "snow_cm": 0,
              "humidity": 97,
              "cloud": 68,
              "feelslike_c": 18.1,
              "feelslike_f": 64.7,
              "windchill_c": 18.1,
              "windchill_f": 64.7,
              "heatindex_c": 18.1,
              "heatindex_f": 64.7,
              "dewpoint_c": 17.7,
              "dewpoint_f": 63.8,
              "will_it_rain": 1,
              "chance_of_rain": 100,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 3.9,
              "gust_kph": 6.3,
              "uv": 0.2
            },
            {
              "time_epoch": 1728646200,
              "time": "2024-10-11 17:00",
              "temp_c": 17,
              "temp_f": 62.6,
              "is_day": 0,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
                "code": 1240
              },
              "wind_mph": 2.5,
              "wind_kph": 4,
              "wind_degree": 221,
              "wind_dir": "SW",
              "pressure_mb": 1011,
              "pressure_in": 29.85,
              "precip_mm": 0.15,
              "precip_in": 0.01,
              "snow_cm": 0,
              "humidity": 98,
              "cloud": 69,
              "feelslike_c": 17,
              "feelslike_f": 62.6,
              "windchill_c": 17,
              "windchill_f": 62.6,
              "heatindex_c": 17,
              "heatindex_f": 62.6,
              "dewpoint_c": 16.7,
              "dewpoint_f": 62,
              "will_it_rain": 1,
              "chance_of_rain": 100,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 4.9,
              "gust_kph": 7.8,
              "uv": 0
            },
            {
              "time_epoch": 1728649800,
              "time": "2024-10-11 18:00",
              "temp_c": 17.8,
              "temp_f": 64,
              "is_day": 0,
              "condition": {
                "text": "Fog",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/248.png",
                "code": 1135
              },
              "wind_mph": 2.7,
              "wind_kph": 4.3,
              "wind_degree": 227,
              "wind_dir": "SW",
              "pressure_mb": 1012,
              "pressure_in": 29.88,
              "precip_mm": 0.04,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 97,
              "cloud": 100,
              "feelslike_c": 17.8,
              "feelslike_f": 64,
              "windchill_c": 17.8,
              "windchill_f": 64,
              "heatindex_c": 17.8,
              "heatindex_f": 64,
              "dewpoint_c": 17.4,
              "dewpoint_f": 63.2,
              "will_it_rain": 1,
              "chance_of_rain": 77,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 0,
              "vis_miles": 0,
              "gust_mph": 4.7,
              "gust_kph": 7.6,
              "uv": 0
            },
            {
              "time_epoch": 1728653400,
              "time": "2024-10-11 19:00",
              "temp_c": 18.1,
              "temp_f": 64.5,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 2.5,
              "wind_kph": 4,
              "wind_degree": 228,
              "wind_dir": "SW",
              "pressure_mb": 1013,
              "pressure_in": 29.91,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 96,
              "cloud": 46,
              "feelslike_c": 18.1,
              "feelslike_f": 64.5,
              "windchill_c": 18.1,
              "windchill_f": 64.5,
              "heatindex_c": 18.1,
              "heatindex_f": 64.5,
              "dewpoint_c": 17.5,
              "dewpoint_f": 63.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 4.1,
              "gust_kph": 6.7,
              "uv": 0
            },
            {
              "time_epoch": 1728657000,
              "time": "2024-10-11 20:00",
              "temp_c": 18.1,
              "temp_f": 64.6,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 2.7,
              "wind_kph": 4.3,
              "wind_degree": 224,
              "wind_dir": "SW",
              "pressure_mb": 1013,
              "pressure_in": 29.92,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 95,
              "cloud": 34,
              "feelslike_c": 18.1,
              "feelslike_f": 64.6,
              "windchill_c": 18.1,
              "windchill_f": 64.6,
              "heatindex_c": 18.1,
              "heatindex_f": 64.6,
              "dewpoint_c": 17.3,
              "dewpoint_f": 63.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 4.5,
              "gust_kph": 7.2,
              "uv": 0
            },
            {
              "time_epoch": 1728660600,
              "time": "2024-10-11 21:00",
              "temp_c": 17.8,
              "temp_f": 64.1,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 2.9,
              "wind_kph": 4.7,
              "wind_degree": 226,
              "wind_dir": "SW",
              "pressure_mb": 1014,
              "pressure_in": 29.93,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 94,
              "cloud": 28,
              "feelslike_c": 17.8,
              "feelslike_f": 64.1,
              "windchill_c": 17.8,
              "windchill_f": 64.1,
              "heatindex_c": 17.8,
              "heatindex_f": 64.1,
              "dewpoint_c": 16.9,
              "dewpoint_f": 62.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 5,
              "gust_kph": 8.1,
              "uv": 0
            },
            {
              "time_epoch": 1728664200,
              "time": "2024-10-11 22:00",
              "temp_c": 17.7,
              "temp_f": 63.8,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 2.9,
              "wind_kph": 4.7,
              "wind_degree": 226,
              "wind_dir": "SW",
              "pressure_mb": 1014,
              "pressure_in": 29.94,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 95,
              "cloud": 30,
              "feelslike_c": 17.7,
              "feelslike_f": 63.8,
              "windchill_c": 17.7,
              "windchill_f": 63.8,
              "heatindex_c": 17.7,
              "heatindex_f": 63.8,
              "dewpoint_c": 16.8,
              "dewpoint_f": 62.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 5,
              "gust_kph": 8.1,
              "uv": 0
            },
            {
              "time_epoch": 1728667800,
              "time": "2024-10-11 23:00",
              "temp_c": 17.5,
              "temp_f": 63.5,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 2.9,
              "wind_kph": 4.7,
              "wind_degree": 231,
              "wind_dir": "SW",
              "pressure_mb": 1014,
              "pressure_in": 29.93,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 95,
              "cloud": 35,
              "feelslike_c": 17.5,
              "feelslike_f": 63.5,
              "windchill_c": 17.5,
              "windchill_f": 63.5,
              "heatindex_c": 17.5,
              "heatindex_f": 63.5,
              "dewpoint_c": 16.7,
              "dewpoint_f": 62.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 5.1,
              "gust_kph": 8.2,
              "uv": 0
            }
          ]
        }
      ]
    }
  }